#!/usr/bin/env python
"""Make survey maps"""
from optparse import OptionParser
from enrico.survey import MapMaker

usage = 'enrico_survey input_dir output_dir'
parser = OptionParser(description=__doc__,
                      usage=usage)
steps = MapMaker.STEPS
steps_str = ','.join(steps)
parser.add_option("--steps", default=steps_str,
                  help="Comma-separated list of preprocessing steps "
                  "to execute (default=%default). Available: "
                  + steps_str)
(options, args) = parser.parse_args()

try:
    input_dir = args[0]
    output_dir = args[1]
    steps = options.steps.split(',')
except Exception as e:
    parser.print_help()
    exit()

map_maker = MapMaker(input_dir, output_dir)
map_maker.process(steps=steps)

