#!/usr/bin/env python
"""A simple script to run a fit and energy bin fit"""

import sys
from enrico.RunGTlike import run

try :
	infile = sys.argv[1]
except :
	print('FATAL: Config file not found.')
	sys.exit(1)

run(infile)
