#!/usr/bin/env python
"""Check setup and / or download missing files."""
from optparse import OptionParser
import enrico.environ

parser = OptionParser(description=__doc__)
parser.add_option("-c", "--check", 
                  action="store_true", default=False,
                  help="Check setup (default=%default)")
parser.add_option("--download_aux", 
                  action="store_true", default=False,
                  help="Download missing catalog and diffuse model "
                  "files (default=%default)")
parser.add_option("--download_data", 
                  action="store_true", default=False,
                  help="Download missing spacecraft and photon "
                  "files (default=%default)")
available = [sel[0] for sel in enrico.environ.SELECTIONS]
parser.add_option("--prepare_data", default=None,
                  help="Comma-separated list of selections to " 
                  "preprocess (default=%default), one of "
                  + ','.join(available))
(options, args) = parser.parse_args()

if not (options.check or options.download_aux or 
        options.download_data or options.prepare_data):
    parser.print_help()
if options.check:
    enrico.environ.check()
if options.download_aux:
    enrico.environ.download_aux()
if options.download_data:
    enrico.environ.download_data()
if options.prepare_data:
    enrico.environ.PrepareData(options.prepare_data)
