#!/usr/bin/env python
"""A simple example how to make a chi2 fit to some flux points"""
import pyfits
data = pyfits.getdata('_2FGLJ1555.7+1111_8bins_likeSEDout.fits', 'DATA FLUX')
energy = data.field('Center Energy')
flux = data.field('dN/dE')
flux_err = data.field('dN/dE_Error')


def pl(energy, norm, gamma):
    """Power law model definition"""
    return norm * energy ** gamma

# Perform the fit
from scipy.optimize import curve_fit
print curve_fit(pl, energy, flux, [1, -2], flux_err, full_output=True)
