#!/usr/bin/env python
"""A simple script to plot a SED"""

import sys
from enrico.pyPlot import PlotSED

try :
	infile = sys.argv[1]
except :
	print('FATAL: Config file not found.')
	sys.exit(1)

PlotSED(infile)
