#!/usr/bin/env python
"""Command line tool to make xml files from the 2FGL catalog
including diffuse models. Calls user contributed make2FGLxml module."""
from optparse import OptionParser
from enrico.config import get_config
import enrico.XmlModel_Generator 
import enrico.environ as env
import os,sys

# Parse command line options
parser = OptionParser(usage="""usage: %prog configfile catalog""",
                      description=__doc__)
(options, args) = parser.parse_args()
if len(args) < 1:
    print('ERROR: You have to give a config file.')
    parser.print_help()
    import sys; sys.exit()

config = get_config(args[0])

folder = config['out']
os.system('mkdir -p '+folder)

# test if the user provide a catalog or not.
#if not use the default one
if config['environ']['FERMI_CATALOG_DIR']=='':
	catalogDir = env.CATALOG_DIR
	print "use the default location of the catalog"
else :
	catalogDir = config['environ']['FERMI_CATALOG_DIR']

if config['environ']['FERMI_CATALOG']=='':
	catalog = catalogDir+"/"+env.CATALOG
	print "use the default catalog"
else :
	catalog = catalogDir+"/"+config['environ']['FERMI_CATALOG']

print "Use the catalog : ",catalog

lib,doc = enrico.XmlModel_Generator.CreateLib()
srclist =enrico.XmlModel_Generator.GetlistFromFits(config,catalog)
enrico.XmlModel_Generator.WriteXml(lib,doc,srclist,config)
enrico.XmlModel_Generator.Xml_to_Reg(folder+"/Roi_model",srclist,Prog = sys.argv[0])
