#!/usr/bin/env python
"""A simple script to make a LC"""

import sys
from enrico.LightCurve import MakeLC

try :
	infile = sys.argv[1]
except :
	print('FATAL: Config file not found.')
	sys.exit(1)

MakeLC(infile)
