#!/usr/bin/env python
"""Command line tool for easy Fermi analysis"""
from os.path import join
import site

import enrico
enrico.check_installation()

print("I can find my data:")
filename = join(site.USER_BASE, 'enrico/default.conf')
print(open(filename).read())