#!/usr/bin/env python
"""A simple script to run a fit and energy bin fit on the cluster"""

import sys,os
from enrico.RunGTlike import run
from enrico.config import get_config

try :
	infile = sys.argv[1]
except :
	print('FATAL: Config file not found.')
	sys.exit(1)


Configuration = get_config(infile)

prefix =Configuration['out']+"/"+Configuration['target']['name']+"_"+Configuration['analysis']['likelihood']+"_"+Configuration['file']['tag']

os.system("mkdir -p "+Configuration['out']+"\n")

scriptname=prefix+".sh"

FILE=open(scriptname,"w")
FILE.write("#!/bin/sh\n")

FILE.write("echo ~~~~~~~~ SETUP ENVIRONMENT ~~~~~~~~ \n")
FILE.write("export ENRICO_DIR=/home/hfm/sanchez/disk/enrico/\n")
FILE.write("source $ENRICO_DIR/init.sh\n")

#### RUN GTLIKE
FILE.write("echo ~~~~~~~~ GO FOR GTLIKE ANALYSIS ~~~~~~~~ \n")
FILE.write("cp "+infile+" .\n")
FILE.write("enrico_fit "+infile+"\n")
FILE.close()

os.system("chmod +x "+scriptname + "\n")
os.system("qsub "+scriptname)
