#!/usr/bin/env python
"""Command line tool to make xml files from the 2FGL catalog
including diffuse models. Calls user contributed make2FGLxml module."""
from optparse import OptionParser
from enrico.config import get_config
from enrico.xml import SourceList

# Parse command line options
parser = OptionParser(usage="""usage: %prog configfile""",
                      description=__doc__)
(options, args) = parser.parse_args()
if len(args) < 1:
    print('ERROR: You have to give a config file.')
    parser.print_help()
    import sys; sys.exit()

config = get_config(args[0])
#import sys; config.write(sys.stdout)
source_list = SourceList(config)
source_list.makeModel()
