#!/usr/bin/env python
"""Command line tool to make xml files from the 2FGL catalog
including diffuse models. Calls user contributed make2FGLxml module."""
from optparse import OptionParser
from enrico.config import get_config
import enrico.XmlModel_Generator 

# Parse command line options
parser = OptionParser(usage="""usage: %prog configfile catalog""",
                      description=__doc__)
(options, args) = parser.parse_args()
if len(args) < 2:
    print('ERROR: You have to give a config file or a catalog.')
    parser.print_help()
    import sys; sys.exit()

config = get_config(args[0])
Catalog=args[1]


lib,doc = enrico.XmlModel_Generator.CreateLib()
srclist =enrico.XmlModel_Generator.GetlistFromFits(config,Catalog)
enrico.XmlModel_Generator.WriteXml(lib,doc,srclist,config)
