#!/usr/bin/env python
"""Query required options and write to a config file"""
import sys
from enrico.config import query_config

try :
	infile = sys.argv[1]
except :
	print('Usage: enrico_config <output config file name>')
	sys.exit(1)



config = query_config()
config.write(open(sys.argv[1], 'w'))
