#!/usr/bin/env python
"""Query required options and write to a config file"""
import sys
from enrico.config import query_config

if len(sys.argv) < 2:
    print('Usage: enrico_config <output config file name>')

config = query_config()
config.write(open(sys.argv[1], 'w'))