#!/usr/bin/env python
"""A simple script to run a fit and energy bin fit on the cluster"""

import sys,os
from enrico.config import get_config
import enrico.environ as environ
from enrico.submit import call
try :
	infile = os.path.abspath(sys.argv[1])
except :
	print('FATAL: Config file not found.')
	sys.exit(1)

enricodir = environ.DIRS.get('ENRICO_DIR')

Configuration = get_config(infile)

if Configuration['Spectrum']['SummedLike'] =='yes' :
	GenericName = Configuration['target']['name']+"_"+Configuration['analysis']['likelihood']+"_Summed_"+Configuration['file']['tag']
else :
	GenericName = Configuration['target']['name']+"_"+Configuration['analysis']['likelihood']+"_Normal_"+Configuration['file']['tag']

prefix =Configuration['out']+"/"+GenericName

os.system("mkdir -p "+Configuration['out']+"\n")
#os.system("cp "+infile+" "+Configuration['out']+"\n")


cmd = "enrico_fit "+infile

scriptname=prefix+"_Script.sh"
JobLog = prefix+"_Job.log"
JobName = GenericName

call(cmd,enricodir,scriptname,JobLog,JobName)

